# Generated by Django 3.0 on 2021-03-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20210317_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='pertence',
        ),
    ]
